proyecto/apps/blog/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, ArticleListView


app_name = 'blog'

urlpatterns = [
	path('', HomeView.as_view(), name='home'),

    path('<slug:slug>/articulo/',
         ArticleDetailView.as_view(),
         name='article_details'),

    path('listado/articulos/',
         ArticleListView.as_view(),
         name='article_list'),


]

proyecto/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proyecto.apps.blog.urls')),


    ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

proyecto/apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from proyecto.apps.core.models import CoreTimeModel
from django.utils.translation import gettext as _
from tinymce_4.fields import TinyMCEModelField


class ConfigBlog(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_config_blog',
        null=True
    )

    name_page = models.CharField(
        verbose_name=_('Nombre de la Pagina'),
        max_length=128
    )

    image = models.ImageField(
        verbose_name=_('Imagen'),
        upload_to='slider-blog-image/'
    )

    content = TinyMCEModelField(
        verbose_name=_('Descripccion de la pagina'),
        blank=True,
        null=True
    )

    def __str__(self):
        return "{}".format(self.name_page)

    class Meta:
        verbose_name = _("Blog configuracion")
        verbose_name_plural = _("blogs Configuraciones")


class CategoryArticle(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_category',
        null=True
    )

    title = models.CharField(
        verbose_name=_('Título'),
        max_length=128
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=128
    )

    image = models.ImageField(
        verbose_name=_('Imagen'),
        upload_to='blog-images/'
    )

    video = models.TextField(
        verbose_name=_('Video'),
        blank=True,
        null=True
    )

    highlighting_weight = models.PositiveIntegerField(
        verbose_name=_("Peso relativo de destaque"),
        default=100
    )

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        verbose_name = _("Categoria")
        verbose_name_plural = _("Categorias")


class BlogArticle(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_articles',
        null=True
    )
    category = models.ForeignKey(
        CategoryArticle,
        verbose_name=_('Categoria'),
        on_delete=models.PROTECT,
        related_name='category_article',
        null=True
    )

    title = models.CharField(
        verbose_name=_('Título'),
        max_length=128
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=128
    )

    image = models.ImageField(
        verbose_name=_('Imagen'),
        upload_to='blog-images/'
    )

    video = models.TextField(
        verbose_name=_('Video'),
        blank=True,
        null=True
    )

    highlighting_weight = models.PositiveIntegerField(
        verbose_name=_("Peso relativo de destaque"),
        default=100
    )

    content = TinyMCEModelField(
        verbose_name=_('Políticas de protección de datos'),
        blank=True,
        null=True
    )

    tags = models.ManyToManyField(
        'BlogTag',
        blank=True
    )

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        verbose_name = _("Artículo")
        verbose_name_plural = _("Artículos")


class BlogTag(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_tag',
        null=True
    )

    name = models.CharField(
        verbose_name=_('Nombre'),
        max_length=128
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=128,
        unique=False
    )

    color = models.PositiveIntegerField(
        verbose_name=_('Color'),
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Etiqueta de articulo")
        verbose_name_plural = _("Etiquetas de los articulos")

proyecto/apps/blog/views.py
import json
from django.shortcuts import render
from django.http.response import JsonResponse, HttpResponse
from django.views.generic import TemplateView, ListView
from proyecto.apps.blog.models import BlogArticle, CategoryArticle, BlogTag, ConfigBlog
from django.shortcuts import get_object_or_404


class HomeView(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lists_articles = BlogArticle.objects.all()

        context.update(
            {
                "lists_articles": lists_articles,
            }
        )
        return context

class ArticleDetailView(TemplateView):

    template_name = 'blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = get_object_or_404(BlogArticle, slug=self.kwargs['slug'])
        list_categorias = CategoryArticle.objects.all()
        list_tags = BlogTag.objects.all()

        context.update(
            {
                "article": article,
                "list_categorias": list_categorias,
                "list_tags": list_tags
            }
        )
        return context

class ArticleListView(ListView):

    paginate_by = 9
    template_name = 'blog_list.html'

    def get_queryset(self):
        queryset = BlogArticle.objects.all() 
        return queryset

        

proyecto/apps/blog/templates/blog_detail.html
{% extends "web/base.html" %}
{% load static %}
{% block social_facebook %}
  <meta property="og:url"           content="" />
  <meta property="og:type"          content="article" />
  <meta property="og:title"         content="" />
  <meta property="og:description"   content="" />
  <meta property="og:image"         content="" />
  <meta property="og:image:width"   content="300"/>
  <meta property="og:image:height"   content="300" />

{% endblock social_facebook %}

{% block css %}
{% endblock css %}
{% block content %}
<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('{{article.image.url}}');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
      <div class="col-md-9 ftco-animate pb-5 text-center">
        <h1 class="mb-3 bread">{{article.title}}</h1>
        <p class="breadcrumbs">
          <span class="mr-2">
            <a href="{% url 'blog:home' %}">Home <i class="ion-ios-arrow-forward"></i></a>
          </span> 
          <span class="mr-2"><a href="{% url 'blog:home' %}">Articulo <i class="ion-ios-arrow-forward"></i></a></span> 
          <span>{{article.title}} <i class="ion-ios-arrow-forward"></i></span>
        </p>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section ftco-degree-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 ftco-animate">
        <p class="mb-5">
          <img src="{{article.image.url}}" alt="" class="img-fluid">
        </p>
        <h2 class="mb-3">{{article.title}}</h2>
        {{article.content|safe}}
        <div class="tag-widget post-tag-container mb-5 mt-5">
          <div class="tagcloud">
            
            {% for tag in article.tags.all %}
            <a href="#" class="tag-cloud-link">{{tag.name}}</a>
            {% endfor %}
          </div>
        </div>
        
        <div class="about-author d-flex p-4 bg-light">
          <div class="bio mr-5 img-back-fluid" style="background-image: url('{{article.user.user_userprofile.image.url}}');">

          </div>
          <div class="desc">
            <h3>{{article.user.user_userprofile.first_name}} {{article.user.user_userprofile.last_name}}</h3>
            <p>{{article.user.user_userprofile.ocupation}}</p>
          </div>
        </div>


{% comment %}
<div class="pt-5 mt-5">
  <h3 class="mb-5">6 Comments</h3>
  <ul class="comment-list">
    <li class="comment">
      <div class="vcard bio">
        <img src="images/person_1.jpg" alt="Image placeholder">
      </div>
      <div class="comment-body">
        <h3>John Doe</h3>
        <div class="meta mb-3">November 13, 2019 at 2:21pm</div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
        <p><a href="#" class="reply">Reply</a></p>
      </div>
    </li>

    <li class="comment">
      <div class="vcard bio">
        <img src="images/person_1.jpg" alt="Image placeholder">
      </div>
      <div class="comment-body">
        <h3>John Doe</h3>
        <div class="meta mb-3">November 13, 2019 at 2:21pm</div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
        <p><a href="#" class="reply">Reply</a></p>
      </div>

      <ul class="children">
        <li class="comment">
          <div class="vcard bio">
            <img src="images/person_1.jpg" alt="Image placeholder">
          </div>
          <div class="comment-body">
            <h3>John Doe</h3>
            <div class="meta mb-3">November 13, 2019 at 2:21pm</div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
            <p><a href="#" class="reply">Reply</a></p>
          </div>


          <ul class="children">
            <li class="comment">
              <div class="vcard bio">
                <img src="images/person_1.jpg" alt="Image placeholder">
              </div>
              <div class="comment-body">
                <h3>John Doe</h3>
                <div class="meta mb-3">November 13, 2019 at 2:21pm</div>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                <p><a href="#" class="reply">Reply</a></p>
              </div>

                <ul class="children">
                  <li class="comment">
                    <div class="vcard bio">
                      <img src="images/person_1.jpg" alt="Image placeholder">
                    </div>
                    <div class="comment-body">
                      <h3>John Doe</h3>
                      <div class="meta mb-3">November 13, 2019 at 2:21pm</div>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                      <p><a href="#" class="reply">Reply</a></p>
                    </div>
                  </li>
                </ul>
            </li>
          </ul>
        </li>
      </ul>
    </li>

    <li class="comment">
      <div class="vcard bio">
        <img src="images/person_1.jpg" alt="Image placeholder">
      </div>
      <div class="comment-body">
        <h3>John Doe</h3>
        <div class="meta mb-3">November 13, 2019 at 2:21pm</div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
        <p><a href="#" class="reply">Reply</a></p>
      </div>
    </li>
  </ul>
  <!-- END comment-list -->
  
  <div class="comment-form-wrap pt-5">
    <h3 class="mb-5">Leave a comment</h3>
    <form action="#" class="p-5 bg-light">
      <div class="form-group">
        <label for="name">Name *</label>
        <input type="text" class="form-control" id="name">
      </div>
      <div class="form-group">
        <label for="email">Email *</label>
        <input type="email" class="form-control" id="email">
      </div>
      <div class="form-group">
        <label for="website">Website</label>
        <input type="url" class="form-control" id="website">
      </div>

      <div class="form-group">
        <label for="message">Message</label>
        <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
      </div>
      <div class="form-group">
        <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
      </div>

    </form>
  </div>
</div>
{% endcomment %}
  


      </div> <!-- .col-md-8 -->
      <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
        <div class="sidebar-box">
          <form action="#" class="search-form">
            <div class="form-group">
              <span class="icon icon-search"></span>
              <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
            </div>
          </form>
        </div>
        <div class="sidebar-box ftco-animate">
          <div class="categories">
            <h3>Categorias</h3>
            {% for categorias in list_categorias.all %}
            <li><a href="#">{{categorias.title}} <span class="ion-ios-arrow-forward"></span></a></li>
            {% endfor %}
              
          </div>
        </div>

        <div class="sidebar-box ftco-animate">
          <h3>Recent Blog</h3>
          {% for article_last in last_articles %}
          <div class="block-21 mb-4 d-flex">
            <a class="blog-img mr-4" style="background-image: url({{article_last.image.url}});"></a>
            <div class="text">
              <h3 class="heading"><a href="#">{{article_last.title}}</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> {{article_last.created|date:"M j Y"}}</a></div>
                <div><a href="#"><span class="icon-person"></span> {{article_last.user}}</a></div>
                {% comment %}
                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                {% endcomment %}
              </div>
            </div>
          </div>
            
          {% endfor %}
            
        </div>

        <div class="sidebar-box ftco-animate">
          <h3>Tags</h3>
          <div class="tagcloud">
            {% for tag in list_tags %}
            <a href="#" class="tag-cloud-link">{{tag.name}}</a>
            {% endfor %}
          </div>
        </div>

{% comment %}
<div class="sidebar-box ftco-animate">
  <h3>Paragraph</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
</div>
{% endcomment %}
  

      </div>

    </div>
  </div>
</section> <!-- .section -->
{% endblock content %}

proyecto/apps/blog/templates/blog_list.html
{% extends "web/base.html" %}
{% load static %}
{% block social_facebook %}
  <meta property="og:url"           content="" />
  <meta property="og:type"          content="article" />
  <meta property="og:title"         content="" />
  <meta property="og:description"   content="" />
  <meta property="og:image"         content="" />
  <meta property="og:image:width"   content="1920"/>
  <meta property="og:image:height"   content="1079" />

{% endblock social_facebook %}

{% block css %}
<style>


</style>

{% endblock css %}
{% block content %}
<div class="hero-wrap js-fullheight" style="background-image: url('{{blog_config.image.url}}');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
      <div class="col-md-12 ftco-animate">
        <h1 class="mb-4 mb-md-0">Listado de Articulos</h1>
        <div class="row">
          <div class="col-md-7">
            <div class="text">
              <div class="mouse">
                <a href="#" class="mouse-icon">
                  <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section bg-light">
  <div class="container">
    <div class="row d-flex">
        {% for article in object_list %}
        <div class="col-md-4 d-flex ftco-animate">
            <div class="blog-entry justify-content-end">
              <a href="{% url 'blog:article_details' article.slug %}" class="block-20" style="background-image: url('{{article.image.url}}');">
              </a>
              <div class="text p-4 float-right d-block">
                <div class="topper d-flex align-items-center">
                  <div class="one py-2 pl-3 pr-1 align-self-stretch">
                    <span class="day">{{article.created|date:"j"}}</span>
                  </div>
                  <div class="two pl-0 pr-3 py-2 align-self-stretch">
                    <span class="yr">{{article.created|date:"Y"}}</span>
                    <span class="mos">{{article.created|date:"F"}}</span>
                  </div>
                </div>
                <h3 class="heading mb-3"><a href="#">{{article.title}}</a></h3>
                <p><a href="{% url 'blog:article_details' article.slug %}" class="btn-custom"><span class="ion-ios-arrow-round-forward mr-3"></span>Ver más</a></p>
              </div>
            </div>
          </div>
          
        {% endfor %}
            
    </div>
    <div class="row mt-5">
      <div class="col text-center">
        <div class="block-27">
          {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}
{% block js %}

{% endblock js %}

proyecto/apps/blog/templates/index.html
{% extends "web/base.html" %}
{% load static %}
{% block social_facebook %}
  <meta property="og:url"           content="" />
  <meta property="og:type"          content="article" />
  <meta property="og:title"         content="" />
  <meta property="og:description"   content="" />
  <meta property="og:image"         content="" />
  <meta property="og:image:width"   content="1920"/>
  <meta property="og:image:height"   content="1079" />

{% endblock social_facebook %}

{% block css %}
<style>


</style>

{% endblock css %}
{% block content %}
<div class="hero-wrap js-fullheight" style="background-image: url('{{blog_config.image.url}}');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
      <div class="col-md-12 ftco-animate">
        <h2 class="subheading">Holaaaaaaaa! Bienvenido a.....</h2>
        <h1 class="mb-4 mb-md-0">{{blog_config.name_page}} blog</h1>
        <div class="row">
          <div class="col-md-7">
            <div class="text">
              {{blog_config.content|safe}}
              <div class="mouse">
                <a href="#" class="mouse-icon">
                  <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

 <section class="ftco-section">
   <div class="container">
     <div class="row">
       <div class="col-md-12">

          {% for article in lists_articles %}
          <div class="case">
            <div class="row">
              <div class="col-md-6 col-lg-6 col-xl-8 d-flex">
                <a href="{% url 'blog:article_details' article.slug %}" class="img w-100 mb-3 mb-md-0" style="background-image: url('{{article.image.url}}');"></a>
              </div>
              <div class="col-md-6 col-lg-6 col-xl-4 d-flex">
                <div class="text w-100 pl-md-3">
                  {% for tag in article.tags.all %}
                  <span class="subheading">{{tag}} </span>
                  {% endfor %}
                  <h2><a href="{% url 'blog:article_details' article.slug %}">{{article.title}}</a></h2>
                  <ul class="media-social list-unstyled">
                  <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                  <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                  <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                </ul>
                  <div class="meta">
                    <p class="mb-0"><a href="#">11/13/2019</a> | <a href="#">12 min read</a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
       </div>
     </div>
     <div class="row mt-5">
      <div class="col text-center">
        <div class="block-27">
          <ul>
            <li><a href="#">&lt;</a></li>
            <li class="active"><span>1</span></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&gt;</a></li>
          </ul>
        </div>
      </div>
    </div>
   </div>
 </section>

{% endblock content %}
{% block js %}

{% endblock js %}