proyecto/apps/blog/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, ArticleListView


app_name = 'blog'

urlpatterns = [
	path('', HomeView.as_view(), name='home'),

    path('<slug:slug>/articulo/',
         ArticleDetailView.as_view(),
         name='article_details'),

    path('listado/articulos/',
         ArticleListView.as_view(),
         name='article_list'),


]

proyecto/apps/core/urls.py
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [

    url(r'^utils/',
        include([
            url(r'^status-task/$',
                views.StatusTaskAPIView.as_view(),
                name="status-task"),
        ])),

]

urlpatterns = format_suffix_patterns(urlpatterns)

proyecto/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proyecto.apps.blog.urls')),


    ] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
     static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

proyecto/apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from proyecto.apps.core.models import CoreTimeModel
from django.utils.translation import gettext as _
from tinymce_4.fields import TinyMCEModelField


class ConfigBlog(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_config_blog',
        null=True
    )

    name_page = models.CharField(
        verbose_name=_('Nombre de la Pagina'),
        max_length=128
    )

    image = models.ImageField(
        verbose_name=_('Imagen'),
        upload_to='slider-blog-image/'
    )

    content = TinyMCEModelField(
        verbose_name=_('Descripccion de la pagina'),
        blank=True,
        null=True
    )

    def __str__(self):
        return "{}".format(self.name_page)

    class Meta:
        verbose_name = _("Blog configuracion")
        verbose_name_plural = _("blogs Configuraciones")


class CategoryArticle(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_category',
        null=True
    )

    title = models.CharField(
        verbose_name=_('Título'),
        max_length=128
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=128
    )

    image = models.ImageField(
        verbose_name=_('Imagen'),
        upload_to='blog-images/'
    )

    video = models.TextField(
        verbose_name=_('Video'),
        blank=True,
        null=True
    )

    highlighting_weight = models.PositiveIntegerField(
        verbose_name=_("Peso relativo de destaque"),
        default=100
    )

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        verbose_name = _("Categoria")
        verbose_name_plural = _("Categorias")


class BlogArticle(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_articles',
        null=True
    )
    category = models.ForeignKey(
        CategoryArticle,
        verbose_name=_('Categoria'),
        on_delete=models.PROTECT,
        related_name='category_article',
        null=True
    )

    title = models.CharField(
        verbose_name=_('Título'),
        max_length=128
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=128
    )

    image = models.ImageField(
        verbose_name=_('Imagen'),
        upload_to='blog-images/'
    )

    video = models.TextField(
        verbose_name=_('Video'),
        blank=True,
        null=True
    )

    highlighting_weight = models.PositiveIntegerField(
        verbose_name=_("Peso relativo de destaque"),
        default=100
    )

    content = TinyMCEModelField(
        verbose_name=_('Políticas de protección de datos'),
        blank=True,
        null=True
    )

    tags = models.ManyToManyField(
        'BlogTag',
        blank=True
    )

    def __str__(self):
        return "{}".format(self.title)

    class Meta:
        verbose_name = _("Artículo")
        verbose_name_plural = _("Artículos")


class BlogTag(CoreTimeModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_tag',
        null=True
    )

    name = models.CharField(
        verbose_name=_('Nombre'),
        max_length=128
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=128,
        unique=False
    )

    color = models.PositiveIntegerField(
        verbose_name=_('Color'),
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Etiqueta de articulo")
        verbose_name_plural = _("Etiquetas de los articulos")

proyecto/apps/core/models.py
from django.db import models
from django.utils.translation import gettext as _

from .managers import RemovedManager, ActiveManager


class CoreTimeModel(models.Model):
    """ Modelo Base"""
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)

    class Meta:
        abstract = True


class CoreActiveModel(models.Model):
    """Modelo Activo"""
    is_active = models.BooleanField(_('is active'), default=True)
    objects = models.Manager()
    active = ActiveManager()

    class Meta:
        abstract = True


class CorePositionModel(models.Model):
    """Modelo Posicion"""
    position = models.IntegerField(_('Position'), default=1)

    class Meta:
        verbose_name = "CorePositionModel"
        verbose_name_plural = "CorePositionModels"
        abstract = True
        ordering = ['position']


class RemovedModel(models.Model):
    is_removed = models.BooleanField(default=False)
    remove_objects = RemovedManager()

    class Meta:
        verbose_name = "Delete Model"
        verbose_name_plural = "Delete Models"
        abstract = True

    def __str__(self):
        pass

proyecto/apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from proyecto.apps.core.models import CoreTimeModel
from django.utils.translation import gettext as _
# Create your models here.

class UserProfile(CoreTimeModel):

    user = models.OneToOneField(
        User,
        verbose_name=_('Usuario'),
        on_delete=models.PROTECT,
        related_name='user_userprofile',
        null=True
    )

    first_name = models.CharField(
        verbose_name=_('Nombre'),
        max_length=128
    )

    last_name = models.CharField(
        verbose_name=_('Apellidos'),
        max_length=128
    )
    ocupation = models.CharField(
        verbose_name=_('Ocupacion/Cargo/Puesto/Trabajo'),
        max_length=128,
        null=True,
        blank=True
    )

    image = models.ImageField(
        verbose_name=_('Imagen_Usuario'),
        upload_to='userprofile-images/', 
        null=True
    )

    slug = models.SlugField(
        verbose_name=_('Slug'),
        max_length=128,
        unique=False
    )

    facebook_url = models.URLField(
        verbose_name=_('URL de cuenta en Facebook'),
        blank=True,
        null=True
    )

    linkedin_url = models.URLField(
        verbose_name=_('URL de cuenta en Linkedin'),
        blank=True,
        null=True
    )

    twitter_url = models.URLField(
        verbose_name=_('URL de cuenta en Twitter'),
        blank=True,
        null=True
    )

    instagram_url = models.URLField(
        verbose_name=_('URL de cuenta en instagram'),
        blank=True,
        null=True
    )

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = _("Perfil del Usuario")
        verbose_name_plural = _("Perfiles de Usuarios")

proyecto/apps/blog/views.py
import json
from django.shortcuts import render
from django.http.response import JsonResponse, HttpResponse
from django.views.generic import TemplateView, ListView
from proyecto.apps.blog.models import BlogArticle, CategoryArticle, BlogTag, ConfigBlog
from django.shortcuts import get_object_or_404


class HomeView(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lists_articles = BlogArticle.objects.all()

        context.update(
            {
                "lists_articles": lists_articles,
            }
        )
        return context

class ArticleDetailView(TemplateView):

    template_name = 'blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = get_object_or_404(BlogArticle, slug=self.kwargs['slug'])
        list_categorias = CategoryArticle.objects.all()
        list_tags = BlogTag.objects.all()

        context.update(
            {
                "article": article,
                "list_categorias": list_categorias,
                "list_tags": list_tags
            }
        )
        return context

class ArticleListView(ListView):

    paginate_by = 9
    template_name = 'blog_list.html'

    def get_queryset(self):
        queryset = BlogArticle.objects.all() 
        return queryset

        

proyecto/templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blogpy - Blog de apoyo, noticias sobre Programacion </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block social_facebook %}

    {% endblock social_facebook %}
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/animate.css' %} ">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %} ">
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
  </head>
  <body>
        {% include "web/header.html" %}

        {% block content %}

        {% endblock content %}

        {% include "web/footer.html" %}

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'js/jquery.min.js' %} "></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %} "></script>
  <script src="{% static 'js/popper.min.js' %} "></script>
  <script src="{% static 'js/bootstrap.min.js' %} "></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %} "></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %} "></script>
  <script src="{% static 'js/jquery.stellar.min.js' %} "></script>
  <script src="{% static 'js/owl.carousel.min.js' %} "></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %} "></script>
  <script src="{% static 'js/aos.js' %} "></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %} "></script>
  <script src="{% static 'js/scrollax.min.js' %} "></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %} "></script>
  <script src="{% static 'js/main.js' %} "></script>
    
  </body>
</html>

proyecto/templates/web/footer.html
{% load static %}  
<footer class="ftco-footer ftco-bg-dark ftco-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="logo"><a href="#">{{blog_config.name_page}}<span>blog</span>.</a></h2>
          <p>{{blog_config.content|safe}}</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
         <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Ultimos articulos</h2>
          
          {% for article_last in last_articles %}
          <div class="block-21 mb-4 d-flex">
            <a class="img mr-4 rounded" style="background-image: url({{article_last.image.url}});"></a>
            <div class="text">
              <h3 class="heading"><a href="#">{{article_last.title}}</a></h3>
              <div class="meta">
                <div><a href="#"></span>{{article_last.created|date:"j M Y"}}</a></div>
                <div><a href="#"></span> {{article_last.user}}</a></div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-5">
          <h2 class="ftco-heading-2">Information</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Home</a></li>
            <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>About</a></li>
            <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Articles</a></li>
            <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Contact</a></li>
          </ul>
        </div>
      </div>
      
      {% comment %}
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Have a Questions?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
              <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
              <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
            </ul>
          </div>
        </div>
      </div>
      {% endcomment %}
        

    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </div>
</footer>

proyecto/templates/web/header.html
{% load static %}

<style>
  li.nav-item .icon-user {
    font-size: 30px;
  }
  li.nav-item.icon_nav {
      display: flex;
  }
  li.nav-item.icon_nav {
    display: flex;
    align-items: center;
}

</style>
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'blog:home' %}">Blog<i>py</i>.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="{% url 'blog:home' %}" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="{% url 'blog:article_list' %}" class="nav-link">Articulos</a></li>
        <li class="nav-item icon_nav"><a href="#"><span class="icon-user"></span></a></li>
        {% comment %}
        <li class="nav-item"><a href="{% url 'blog:home' %}" class="nav-link">Team</a></li>
        <li class="nav-item"><a href="{% url 'blog:home' %}" class="nav-link">Contact</a></li>
        {% endcomment %}
      </ul>
    </div>
  </div>
</nav>